export const departments: string[] = [
    "Anesthesia",
    "Anatomy",
    "Cardiology",
    "Dermatology",
    "Dentistry",
    "Emergency Medicine",
    "Endocrinology",
    "ENT",
    "Forensic Medicine & Toxicology",
    "Gastroenterology",
    "Geriatric Medicine",
    "Gynecology",
    "Hematology",
    "Infertility & IVF",
    "Medical Surgical",
    "Medicine",
    "Nephrology",
    "Neurology",
    "Surgery",
    "Ophthalmology",
    "Out Patient Department OPD",
    "Orthopedics",
    "Pediatrics",
    "Physical Medicine & Rehabilitation",
    "Physiology",
    "Physiotherapy",
    "Plastic Surgery",
    "Pulmonary Medicine and sleep disorders",
    "Psychiatry",
    "Rheumatology",
    "Surgery",
    "Urology",
    "Lab Technician",
    "Blood Bank",
    "Biochemistry",
    "Microbiology",
    "Pathology",
    "Pharmacology",
    "Radio diagnosis",
    "Radiographers",
    "OT Technicians",
    "Technicians CSSD",
    "Nursing",
    "Hospital Administration",
    "Laundry",
    "Pharmacist",
    "Dietician",
    "HR",
    "Ward assistance",
  ];